apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
  namespace: default
  labels:
    app: binarycalculator-deployment
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: binarycalculator-deployment
    spec:
      containers:
      - name: binarycalculator
        image: northamerica-northeast2-docker.pkg.dev/tensile-ace-415721/sofe3980u/binarycalculator
        ports:
        - containerPort: 8080
